class Cosmetico {
    constructor(id, categoria, nombre, descripcion, color, precio, imagen) {
        this.id = parseInt(id);
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.imagen = imagen;
        this.color = color;
        this.precio = parseFloat(precio);
        this.categoria = parseInt(categoria);
    }
}

//Cosntantes----------------------------------------------------------------
const mensajeError = "¡UPS! PRODUCTO QUE BUSCAS NO SE ENCUENTRA DISPONIBLE";


const cosmeticos = [];
cosmeticos.push(new Cosmetico(1, 2, "Labial Studio Look Mate", "El favorito de todas. Labial líquido Studio Look mate de larga duración, un must-have para combinar todos tus looks. 6ml / 0.17fl.oz.", "LATTE", 109.90, "https://cyzone.tiendabelcorp.com/cdn-cgi/image/width=1200,fit=contain,f=auto/https://belc-bigdata-mdm-images-prd.s3.amazonaws.com/images/FotoProductoFondoBlancoWebRedes/200103920_fotofondoblanco.jpg"));
cosmeticos.push(new Cosmetico(2, 1, "spray fijador maquillaje studio look", "makeup intacto. el spray fijador hará que tu maquillaje dure por más tiempo además de brindarle un acabado mate a tu rostro. 60ml/2.04 fl.oz", "Transparente", 169.90, "https://cyzone.tiendabelcorp.com/cdn-cgi/image/width=1200,fit=contain,f=auto/https://belc-bigdata-mdm-images-prd.s3.amazonaws.com/images/FotoProductoFondoBlancoWebRedes/200102371_fotofondoblanco.jpg"));
cosmeticos.push(new Cosmetico(3, 3, "Delineador Plumón Studio Look Para Ojos", "Delineado perfecto. Delineador Plumón Studio Look Para Ojos de alta precisión, color negro intenso y fácil aplicación. 1ml.", "Negro", 109.90, "https://cyzone.tiendabelcorp.com/cdn-cgi/image/width=1200,fit=contain,f=auto/https://belc-bigdata-mdm-images-prd.s3.amazonaws.com/images/FotoProductoFondoBlancoWebRedes/210095652_fotofondoblanco.jpg"));
cosmeticos.push(new Cosmetico(4, 2, "Labial Graduable Mate Studio Look", "¡Tú decides la intensidad! Labial en barra con acabado mate de textura ultra ligera 2g.", "Blush nude", 109.98, "https://cyzone.tiendabelcorp.com/cdn-cgi/image/width=1200,fit=contain,f=auto/https://belc-bigdata-mdm-images-prd.s3.amazonaws.com/images/FotoProductoFondoBlancoWebRedes/200098797_fotofondoblanco.jpg"));
cosmeticos.push(new Cosmetico(5, 3, "Delineador De Cejas Plumón 2 En 1 Wow Brow Studio Look", "Cejas naturales contigo todo el día. Delineador De Cejas Plumón 2 En 1 Wow Brow Studio Look de larga duración con efecto microblading 0.6 ml.", "Dark Brown", 154.90, "https://cyzone.tiendabelcorp.com/cdn-cgi/image/width=1200,fit=contain,f=auto/https://belc-bigdata-mdm-images-prd.s3.amazonaws.com/images/FotoProductoFondoBlancoWebRedes/210097511_fotofondoblanco.jpg"));
cosmeticos.push(new Cosmetico(6, 4, "Paleta Para Rostro Studio Look", "5 productos, 1 paleta. La Paleta Para Rostro Studio Look 5 en 1 es la más completa para resaltar, definir, broncear, dar color e iluminar tu rostro.", "Calidos", 229.90, "https://cyzone.tiendabelcorp.com/cdn-cgi/image/width=1200,fit=contain,f=auto/https://belc-bigdata-mdm-images-prd.s3.amazonaws.com/images/FotoProductoFondoBlancoWebRedes/200102276_fotofondoblanco.jpg"));
cosmeticos.push(new Cosmetico(7, 5, "Base de Maquillaje Studio Look Mate de Alta Cobertura", "Base de maquillaje con efecto mate de alta cobertura y larga duración. fsp 20 + uva. 30g.", "Espresso", 209.90, "https://cyzone.tiendabelcorp.com/cdn-cgi/image/width=1200,fit=contain,f=auto/https://belc-bigdata-mdm-images-prd.s3.amazonaws.com/images/FotoProductoFondoBlancoWebRedes/200100849_fotofondoblanco.jpg"));
cosmeticos.push(new Cosmetico(8, 3, "Lápiz Delineador De Ojos En Gel Studio Look", "Este producto es un refill para la paleta personalizable Beauty Box. Polvo facial matificante Blur Evolution. Su acabado mate ayuda a difuminar las imperfecciones del rostro, dejándolo con un aspecto radiante y libre de manchas. Cuenta con FPS 15. Capacidad: 3.5 g / 12 oz.", "Party rose", 119.90, "https://cyzone.tiendabelcorp.com/cdn-cgi/image/width=1200,fit=contain,f=auto/https://belc-bigdata-mdm-images-prd.s3.amazonaws.com/images/FotoProductoFondoBlancoWebRedes/210095973_fotofondoblanco2.jpg"));
cosmeticos.push(new Cosmetico(9, 1, "Loción Hidratante Perfumada Sweet Black", "Tu aroma favorito en loción. Loción hidratante perfumada Sweet Black 130ml.", "Sweet Black", 109.90, "https://cyzone.tiendabelcorp.com/cdn-cgi/image/width=1200,fit=contain,f=auto/https://belc-bigdata-mdm-images-prd.s3.amazonaws.com/images/FotoProductoFondoBlancoWebRedes/200106161_fotofondoblanco.jpg"));
cosmeticos.push(new Cosmetico(10, 1, "Crema hidratante facial en gel skin first", "piel hidratada y cero brillo. la crema hidratante facial en gel dejará tu rostro mate, suave y listo para un maquillaje wow. 50g / 1.7 oz.", "Crema", 169.90, "https://cdn1-prd.beautymovers.com/sys-master/s3medias/h68/hed/10458328465438/200097894_imagenProducto_prodGallery_superZoom"));
cosmeticos.push(new Cosmetico(11, 4, "Paleta de Maquillaje Multifuncional Cheek&Eyes Studio Look", "Looks de acabado natural y de manera fácil con la paleta de maquillaje cheek & eyes para mejillas, ojos y cejas Studio Look 10.5 g", "calidos", 274.90, "https://cyzone.tiendabelcorp.com/cdn-cgi/image/width=1200,fit=contain,f=auto/https://belc-bigdata-mdm-images-prd.s3.amazonaws.com/images/FotoProductoFondoBlancoWebRedes/200102063_fotofondoblanco.jpg"));
cosmeticos.push(new Cosmetico(12, 4, "Paleta De Sombras Compactas Twelve O´Clock", "¡Miles de looks en un solo lugar! Arriésgate con la Paleta De Sombras Compactas Twelve O´Clock de 12 tonos. Conoce la paleta Sunset Heat y su nuevo empaque. 10g. / .35 oz.", "Color fever", 219.90, "https://cyzone.tiendabelcorp.com/cdn-cgi/image/width=1200,fit=contain,f=auto/https://belc-bigdata-mdm-images-prd.s3.amazonaws.com/images/FotoProductoFondoBlancoWebRedes/200096568_fotofondoblanco.jpg"));
cosmeticos.push(new Cosmetico(13, 4, " Sombras de ojos studio look shimmer compactas", "Shimmer-look. Las Sombras de Ojos Studio Look Shimmer Compactas le darán un color intenso, además de larga duración a tu mirada. 2g.", "Shimmer", 109.90, "https://cdn1-prd.beautymovers.com/sys-master/s3medias/h7a/h71/10749424861214/200102272_imagenProducto_prodGallery_superZoom"));
cosmeticos.push(new Cosmetico(14, 4, "sombras de ojos shock eyes shimmer en gel", "instant shock. las sombras de ojos shock eyes shimmer en gel te dejarán un efecto de color intenso todo el día. 5g. / .17 oz.", "Aqua", 109.90, "https://cyzone.tiendabelcorp.com/cdn-cgi/image/width=1200,fit=contain,f=auto/https://belc-bigdata-mdm-images-prd.s3.amazonaws.com/images/FotoProductoWebRedes/200098489_fotoproducto.jpg"));
cosmeticos.push(new Cosmetico(15, 2, "Labial Larga Duración Crayon Lips Retráctil", "Labios full precisión y color. Labial Larga Duración Crayon Lips Retráctil con acabado mate y de color intenso. 2.5g/.08oz.", "Malbec", 89.90, "https://cyzone.tiendabelcorp.com/cdn-cgi/image/width=1200,fit=contain,f=auto/https://belc-bigdata-mdm-images-prd.s3.amazonaws.com/images/FotoProductoFondoBlancoWebRedes/210092118_fotofondoblanco.jpg"));
cosmeticos.push(new Cosmetico(16, 2, "Labial En Barra Hidratante Hydrafull", "labios hidratados y a color hidratación y color con el labial en barra hydrafull fps 15. 4g. / 0.14 oz", "marsala", 69.90, "https://cyzone.tiendabelcorp.com/cdn-cgi/image/width=1200,fit=contain,f=auto/https://belc-bigdata-mdm-images-prd.s3.amazonaws.com/images/FotoProductoFondoBlancoWebRedes/200100221_fotofondoblanco.jpg"));
cosmeticos.push(new Cosmetico(17, 2, "Labial Studio Look Mate Metálico", "Labios metálicos. Labial líquido Studio Look mate de larga duración y acabado metálico. 5ml / 0.17fl.oz.", "Violet", 109.90, "https://cyzone.tiendabelcorp.com/cdn-cgi/image/width=1200,fit=contain,f=auto/https://belc-bigdata-mdm-images-prd.s3.amazonaws.com/images/FotoProductoFondoBlancoWebRedes/200102182_fotofondoblanco.jpg"));
cosmeticos.push(new Cosmetico(18, 5, "Base de Maquillaje Studio Look Mate de Alta Cobertura", "Base de maquillaje con efecto mate de alta cobertura y larga duración. fsp 20 + uva. 30g.", "Almendra", 209.90, "https://cyzone.tiendabelcorp.com/cdn-cgi/image/width=1200,fit=contain,f=auto/https://belc-bigdata-mdm-images-prd.s3.amazonaws.com/images/FotoProductoFondoBlancoWebRedes/200098176_fotofondoblanco.jpg"));
cosmeticos.push(new Cosmetico(19, 5, "Base de Maquillaje Studio Look Mate de Alta Cobertura", "Base de maquillaje con efecto mate de alta cobertura y larga duración. fsp 20 + uva. 30g.", "Chocochip", 209.90, "https://cyzone.tiendabelcorp.com/cdn-cgi/image/width=1200,fit=contain,f=auto/https://belc-bigdata-mdm-images-prd.s3.amazonaws.com/images/FotoProductoFondoBlancoWebRedes/200098183_fotofondoblanco.jpg"));
cosmeticos.push(new Cosmetico(20, 5, "Base de Maquillaje Studio Look Mate de Alta Cobertura", "Base de maquillaje con efecto mate de alta cobertura y larga duración. fsp 20 + uva. 30g.", "Azucar Blanca", 209.90, "https://cyzone.tiendabelcorp.com/cdn-cgi/image/width=1200,fit=contain,f=auto/https://belc-bigdata-mdm-images-prd.s3.amazonaws.com/images/FotoProductoFondoBlancoWebRedes/200098169_fotofondoblanco.jpg"));
cosmeticos.push(new Cosmetico(21, 5, "Base de Maquillaje Studio Look Mate de Alta Cobertura", "Base de maquillaje con efecto mate de alta cobertura y larga duración. fsp 20 + uva. 30g.", "Chantilly", 209.90, "https://cyzone.tiendabelcorp.com/cdn-cgi/image/width=1200,fit=contain,f=auto/https://belc-bigdata-mdm-images-prd.s3.amazonaws.com/images/FotoProductoFondoBlancoWebRedes/200098170_fotofondoblanco.jpg"));

const productoCarrito = [];